# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\研二\肌电项目\代码\EMGLGT-master\mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 896)
        MainWindow.setStyleSheet("/*\n"
" * MacOS Style Sheet for QT Applications\n"
" * Author: Jaime A. Quiroga P.\n"
" * Company: GTRONICK\n"
" * Last updated: 25/12/2020, 23:10.\n"
" * Available at: https://github.com/GTRONICK/QSS/blob/master/MacOS.qss\n"
" */\n"
"QMainWindow {\n"
"    background-color:#ececec;\n"
"}\n"
"QPushButton, QToolButton, QCommandLinkButton{\n"
"    padding: 0 5px 0 5px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #fbfdfd, stop:0.5 #ffffff, stop:1 #fbfdfd);\n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 2px solid transparent;\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    color: #3d3d3d;\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QPushButton:disabled, QToolButton:disabled, QCommandLinkButton:disabled{\n"
"    color: #616161;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #dce7eb, stop:0.5 #e0e8eb, stop:1 #dee7ec);\n"
"}\n"
"QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QTimeEdit, QDateEdit, QDateTimeEdit {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QTimeEdit:focus, QDateEdit:focus, QDateTimeEdit:focus {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}\n"
"QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled, QSpinBox:disabled, QDoubleSpinBox:disabled, QTimeEdit:disabled, QDateEdit:disabled, QDateTimeEdit:disabled {\n"
"    color: #b9b9b9;\n"
"}\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button, QTimeEdit::up-button, QDateEdit::up-button, QDateTimeEdit::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button, QTimeEdit::down-button, QDateEdit::down-button, QDateTimeEdit::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-bottom-right-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QSpinBox::up-button:pressed, QDoubleSpinBox::up-button:pressed, QTimeEdit::up-button:pressed, QDateEdit::up-button:pressed, QDateTimeEdit::up-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QSpinBox::down-button:pressed, QDoubleSpinBox::down-button:pressed, QTimeEdit::down-button:pressed, QDateEdit::down-button:pressed, QDateTimeEdit::down-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover, QTimeEdit::up-button:hover, QDateEdit::up-button:hover, QDateTimeEdit::up-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-top-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"    \n"
"}\n"
"QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover, QTimeEdit::down-button:hover, QDateEdit::down-button:hover, QDateTimeEdit::down-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow, QTimeEdit::up-arrow, QDateEdit::up-arrow, QDateTimeEdit::up-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
"}\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow, QTimeEdit::down-arrow, QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n"
"}\n"
"QProgressBar {\n"
"    max-height: 8px;\n"
"    text-align: center;\n"
"    font: italic bold 11px;\n"
"    color: #3d3d3d;\n"
"    border: 1px solid transparent;\n"
"    border-radius:4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"    border-radius: 4px;\n"
"}\n"
"QProgressBar:disabled {\n"
"    color: #616161;\n"
"}\n"
"QProgressBar::chunk:disabled {\n"
"    background-color: #aeaeae;\n"
"}\n"
"QSlider::groove {\n"
"    border: 1px solid #bbbbbb;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 6px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page, QSlider::sub-page {\n"
"    border: 1px transparent;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::add-page:horizontal:disabled, QSlider::sub-page:horizontal:disabled, QSlider::add-page:vertical:disabled, QSlider::sub-page:vertical:disabled {\n"
"    background: #b9b9b9;\n"
"}\n"
"QComboBox, QFontComboBox {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #272727;\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png); /*Adawaita icon thene*/\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid darkgray;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #dadada;\n"
"    selection-color: #272727;\n"
"    color: #272727;\n"
"    background: white;\n"
"}\n"
"QLabel, QCheckBox, QRadioButton {\n"
"    color: #272727;\n"
"}\n"
"QCheckBox {\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled, QRadioButton:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/object-select-symbolic.symbolic.png);\n"
"    height: 15px;\n"
"    width: 15px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #48a5fd;\n"
"    color: #ffffff;\n"
"    border-radius: 3px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #48a5fd, stop:0.5 #329cfb, stop:1 #48a5fd);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    \n"
"    height: 15px;\n"
"    width: 15px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #48a5fd;\n"
"    border-radius: 3px;\n"
"    background-color: #fbfdfa;\n"
"}\n"
"QLCDNumber {\n"
"    color: #616161;;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #ececec;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #616161;\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background-color: #ececec;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #dadada;\n"
"    color: #3d3d3d;\n"
"}\n"
"QMenu {\n"
"    background-color: #ececec;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #dadada;\n"
"    color: #3d3d3d;\n"
"}\n"
"QMenu::item {\n"
"    color: #616161;;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: #050a0e;\n"
"    background-color: #e0e0e0;\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    position: absolute;\n"
"    top: -0.5em;\n"
"    padding-top: 0.5em;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-bottom: 1px solid #c0c0c0;\n"
"    padding: 3px;\n"
"    color: #272727;\n"
"    background-color: #fefefc;\n"
"    margin-left:0px;\n"
"}\n"
"QTabBar::tab:!last {\n"
"    border-right: 1px solid;\n"
"    border-right-color: #c0c0c0;\n"
"    border-bottom-color: #c0c0c0;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QRadioButton::indicator {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    border-style:solid;\n"
"    border-radius:7px;\n"
"    border-width: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    border-color: #48a5fd;\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:0.4,fx:0.5, fy:0.5, stop:0 #ffffff, stop:0.5 #ffffff, stop:0.6 #48a5fd, stop:1 #48a5fd);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    border-color: #a9b7c6;\n"
"    background-color: #fbfdfa;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"\n"
"QDial {\n"
"    background: #16a085;\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #222b2e;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#222b2e;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    max-height: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: #52595d;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover, QScrollBar::handle:vertical:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    border: 2px transparent grey;\n"
"    border-radius: 4px;\n"
"    subcontrol-origin: margin;\n"
"    background: #b9b9b9;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed, QScrollBar::add-line:horizontal:pressed, QScrollBar::sub-line:horizontal:pressed, QScrollBar::sub-line:vertical:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal, QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-previous-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-next-symbolic.symbolic.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.rightWidget = QtWidgets.QWidget(self.centralwidget)
        self.rightWidget.setObjectName("rightWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.rightWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.filterWidget2 = QtWidgets.QWidget(self.rightWidget)
        self.filterWidget2.setObjectName("filterWidget2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.filterWidget2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.signal_max_label2 = QtWidgets.QLabel(self.filterWidget2)
        self.signal_max_label2.setObjectName("signal_max_label2")
        self.gridLayout_9.addWidget(self.signal_max_label2, 0, 0, 1, 1)
        self.signal_min_label2 = QtWidgets.QLabel(self.filterWidget2)
        self.signal_min_label2.setObjectName("signal_min_label2")
        self.gridLayout_9.addWidget(self.signal_min_label2, 0, 1, 1, 1)
        self.signal_max_val2 = QtWidgets.QLabel(self.filterWidget2)
        self.signal_max_val2.setObjectName("signal_max_val2")
        self.gridLayout_9.addWidget(self.signal_max_val2, 1, 0, 1, 1)
        self.signal_min_val2 = QtWidgets.QLabel(self.filterWidget2)
        self.signal_min_val2.setObjectName("signal_min_val2")
        self.gridLayout_9.addWidget(self.signal_min_val2, 1, 1, 1, 1)
        self.average_label2 = QtWidgets.QLabel(self.filterWidget2)
        self.average_label2.setObjectName("average_label2")
        self.gridLayout_9.addWidget(self.average_label2, 2, 0, 1, 1)
        self.gradient_label2 = QtWidgets.QLabel(self.filterWidget2)
        self.gradient_label2.setObjectName("gradient_label2")
        self.gridLayout_9.addWidget(self.gradient_label2, 2, 1, 1, 1)
        self.average_val2 = QtWidgets.QLabel(self.filterWidget2)
        self.average_val2.setObjectName("average_val2")
        self.gridLayout_9.addWidget(self.average_val2, 3, 0, 1, 1)
        self.gradient_val2 = QtWidgets.QLabel(self.filterWidget2)
        self.gradient_val2.setObjectName("gradient_val2")
        self.gridLayout_9.addWidget(self.gradient_val2, 3, 1, 1, 1)
        self.filtersignal2 = QtWidgets.QWidget(self.filterWidget2)
        self.filtersignal2.setObjectName("filtersignal2")
        self.gridLayout_9.addWidget(self.filtersignal2, 0, 2, 4, 1)
        self.gridLayout_9.setColumnStretch(0, 2)
        self.gridLayout_9.setColumnStretch(1, 2)
        self.gridLayout_9.setColumnStretch(2, 7)
        self.gridLayout_4.addWidget(self.filterWidget2, 2, 0, 1, 1)
        self.rightWidgetTile = QtWidgets.QLabel(self.rightWidget)
        self.rightWidgetTile.setObjectName("rightWidgetTile")
        self.gridLayout_4.addWidget(self.rightWidgetTile, 0, 0, 1, 1)
        self.originalWidget2 = QtWidgets.QWidget(self.rightWidget)
        self.originalWidget2.setObjectName("originalWidget2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.originalWidget2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.energy_entropy_label2 = QtWidgets.QLabel(self.originalWidget2)
        self.energy_entropy_label2.setObjectName("energy_entropy_label2")
        self.gridLayout_7.addWidget(self.energy_entropy_label2, 0, 0, 1, 1)
        self.energy_entropy_val2 = QtWidgets.QLabel(self.originalWidget2)
        self.energy_entropy_val2.setObjectName("energy_entropy_val2")
        self.gridLayout_7.addWidget(self.energy_entropy_val2, 0, 1, 1, 1)
        self.pectral_entropy_label2 = QtWidgets.QLabel(self.originalWidget2)
        self.pectral_entropy_label2.setObjectName("pectral_entropy_label2")
        self.gridLayout_7.addWidget(self.pectral_entropy_label2, 1, 0, 1, 1)
        self.pectral_entropy_val2 = QtWidgets.QLabel(self.originalWidget2)
        self.pectral_entropy_val2.setObjectName("pectral_entropy_val2")
        self.gridLayout_7.addWidget(self.pectral_entropy_val2, 1, 1, 1, 1)
        self.originalsignal2 = QtWidgets.QWidget(self.originalWidget2)
        self.originalsignal2.setObjectName("originalsignal2")
        self.gridLayout_7.addWidget(self.originalsignal2, 0, 2, 2, 1)
        self.gridLayout_7.setColumnStretch(0, 2)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.gridLayout_7.setColumnStretch(2, 8)
        self.gridLayout_4.addWidget(self.originalWidget2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gear_right = QtWidgets.QGraphicsView(self.rightWidget)
        self.gear_right.setObjectName("gear_right")
        self.horizontalLayout_2.addWidget(self.gear_right)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 8)
        self.gridLayout_4.setRowStretch(2, 8)
        self.gridLayout_4.setRowStretch(3, 7)
        self.gridLayout.addWidget(self.rightWidget, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.midWidget = QtWidgets.QWidget(self.centralwidget)
        self.midWidget.setObjectName("midWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.midWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.midWidgetTile = QtWidgets.QLabel(self.midWidget)
        self.midWidgetTile.setObjectName("midWidgetTile")
        self.gridLayout_3.addWidget(self.midWidgetTile, 0, 0, 1, 1)
        self.originalWidget = QtWidgets.QWidget(self.midWidget)
        self.originalWidget.setObjectName("originalWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.originalWidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.energy_entropy_label = QtWidgets.QLabel(self.originalWidget)
        self.energy_entropy_label.setObjectName("energy_entropy_label")
        self.gridLayout_6.addWidget(self.energy_entropy_label, 0, 0, 1, 1)
        self.energy_entropy_val = QtWidgets.QLabel(self.originalWidget)
        self.energy_entropy_val.setObjectName("energy_entropy_val")
        self.gridLayout_6.addWidget(self.energy_entropy_val, 0, 1, 1, 1)
        self.originalsignal = QtWidgets.QWidget(self.originalWidget)
        self.originalsignal.setObjectName("originalsignal")
        self.gridLayout_6.addWidget(self.originalsignal, 0, 2, 2, 1)
        self.pectral_entropy_label = QtWidgets.QLabel(self.originalWidget)
        self.pectral_entropy_label.setObjectName("pectral_entropy_label")
        self.gridLayout_6.addWidget(self.pectral_entropy_label, 1, 0, 1, 1)
        self.pectral_entropy_val = QtWidgets.QLabel(self.originalWidget)
        self.pectral_entropy_val.setObjectName("pectral_entropy_val")
        self.gridLayout_6.addWidget(self.pectral_entropy_val, 1, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 2)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.gridLayout_6.setColumnStretch(2, 8)
        self.gridLayout_3.addWidget(self.originalWidget, 1, 0, 1, 1)
        self.filterWidget = QtWidgets.QWidget(self.midWidget)
        self.filterWidget.setObjectName("filterWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.filterWidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.signal_max_label = QtWidgets.QLabel(self.filterWidget)
        self.signal_max_label.setObjectName("signal_max_label")
        self.gridLayout_8.addWidget(self.signal_max_label, 0, 0, 1, 1)
        self.signal_min_label = QtWidgets.QLabel(self.filterWidget)
        self.signal_min_label.setObjectName("signal_min_label")
        self.gridLayout_8.addWidget(self.signal_min_label, 0, 1, 1, 1)
        self.signal_max_val = QtWidgets.QLabel(self.filterWidget)
        self.signal_max_val.setObjectName("signal_max_val")
        self.gridLayout_8.addWidget(self.signal_max_val, 1, 0, 1, 1)
        self.signal_min_val = QtWidgets.QLabel(self.filterWidget)
        self.signal_min_val.setObjectName("signal_min_val")
        self.gridLayout_8.addWidget(self.signal_min_val, 1, 1, 1, 1)
        self.average_label = QtWidgets.QLabel(self.filterWidget)
        self.average_label.setObjectName("average_label")
        self.gridLayout_8.addWidget(self.average_label, 2, 0, 1, 1)
        self.gradient_label = QtWidgets.QLabel(self.filterWidget)
        self.gradient_label.setObjectName("gradient_label")
        self.gridLayout_8.addWidget(self.gradient_label, 2, 1, 1, 1)
        self.average_val = QtWidgets.QLabel(self.filterWidget)
        self.average_val.setObjectName("average_val")
        self.gridLayout_8.addWidget(self.average_val, 3, 0, 1, 1)
        self.gradient_val = QtWidgets.QLabel(self.filterWidget)
        self.gradient_val.setObjectName("gradient_val")
        self.gridLayout_8.addWidget(self.gradient_val, 3, 1, 1, 1)
        self.filtersignal = QtWidgets.QWidget(self.filterWidget)
        self.filtersignal.setObjectName("filtersignal")
        self.gridLayout_8.addWidget(self.filtersignal, 0, 2, 4, 1)
        self.gridLayout_8.setColumnStretch(0, 2)
        self.gridLayout_8.setColumnStretch(1, 2)
        self.gridLayout_8.setColumnStretch(2, 7)
        self.gridLayout_3.addWidget(self.filterWidget, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gear_left = QtWidgets.QGraphicsView(self.midWidget)
        self.gear_left.setObjectName("gear_left")
        self.horizontalLayout.addWidget(self.gear_left)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 8)
        self.gridLayout_3.setRowStretch(2, 8)
        self.gridLayout_3.setRowStretch(3, 7)
        self.gridLayout.addWidget(self.midWidget, 1, 1, 1, 1)
        self.leftWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftWidget.sizePolicy().hasHeightForWidth())
        self.leftWidget.setSizePolicy(sizePolicy)
        self.leftWidget.setObjectName("leftWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.leftWidget)
        self.gridLayout_2.setContentsMargins(20, 9, 20, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.zw1 = QtWidgets.QLabel(self.leftWidget)
        self.zw1.setObjectName("zw1")
        self.gridLayout_2.addWidget(self.zw1, 8, 0, 1, 1)
        self.fatigueaBtn_2 = QtWidgets.QPushButton(self.leftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fatigueaBtn_2.sizePolicy().hasHeightForWidth())
        self.fatigueaBtn_2.setSizePolicy(sizePolicy)
        self.fatigueaBtn_2.setMaximumSize(QtCore.QSize(105, 56))
        self.fatigueaBtn_2.setObjectName("fatigueaBtn_2")
        self.gridLayout_2.addWidget(self.fatigueaBtn_2, 6, 0, 1, 1)
        self.saveBtn_2 = QtWidgets.QPushButton(self.leftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBtn_2.sizePolicy().hasHeightForWidth())
        self.saveBtn_2.setSizePolicy(sizePolicy)
        self.saveBtn_2.setMaximumSize(QtCore.QSize(105, 56))
        self.saveBtn_2.setObjectName("saveBtn_2")
        self.gridLayout_2.addWidget(self.saveBtn_2, 7, 0, 1, 1)
        self.zw2 = QtWidgets.QLabel(self.leftWidget)
        self.zw2.setObjectName("zw2")
        self.gridLayout_2.addWidget(self.zw2, 12, 0, 1, 1)
        self.zw3 = QtWidgets.QLabel(self.leftWidget)
        self.zw3.setObjectName("zw3")
        self.gridLayout_2.addWidget(self.zw3, 14, 0, 1, 1)
        self.saveBtn_1 = QtWidgets.QPushButton(self.leftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBtn_1.sizePolicy().hasHeightForWidth())
        self.saveBtn_1.setSizePolicy(sizePolicy)
        self.saveBtn_1.setMaximumSize(QtCore.QSize(105, 56))
        self.saveBtn_1.setObjectName("saveBtn_1")
        self.gridLayout_2.addWidget(self.saveBtn_1, 3, 0, 1, 1)
        self.openBtn_2 = QtWidgets.QPushButton(self.leftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openBtn_2.sizePolicy().hasHeightForWidth())
        self.openBtn_2.setSizePolicy(sizePolicy)
        self.openBtn_2.setMaximumSize(QtCore.QSize(105, 56))
        self.openBtn_2.setObjectName("openBtn_2")
        self.gridLayout_2.addWidget(self.openBtn_2, 5, 0, 1, 1)
        self.fatigueaBtn_1 = QtWidgets.QPushButton(self.leftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fatigueaBtn_1.sizePolicy().hasHeightForWidth())
        self.fatigueaBtn_1.setSizePolicy(sizePolicy)
        self.fatigueaBtn_1.setMaximumSize(QtCore.QSize(105, 56))
        self.fatigueaBtn_1.setObjectName("fatigueaBtn_1")
        self.gridLayout_2.addWidget(self.fatigueaBtn_1, 2, 0, 1, 1)
        self.openBtn_1 = QtWidgets.QPushButton(self.leftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openBtn_1.sizePolicy().hasHeightForWidth())
        self.openBtn_1.setSizePolicy(sizePolicy)
        self.openBtn_1.setMaximumSize(QtCore.QSize(105, 56))
        self.openBtn_1.setObjectName("openBtn_1")
        self.gridLayout_2.addWidget(self.openBtn_1, 1, 0, 1, 1)
        self.left_label_1 = QtWidgets.QLabel(self.leftWidget)
        self.left_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.left_label_1.setObjectName("left_label_1")
        self.gridLayout_2.addWidget(self.left_label_1, 0, 0, 1, 1)
        self.left_label_2 = QtWidgets.QLabel(self.leftWidget)
        self.left_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.left_label_2.setObjectName("left_label_2")
        self.gridLayout_2.addWidget(self.left_label_2, 4, 0, 1, 1)
        self.comboBox_value = QtWidgets.QComboBox(self.leftWidget)
        self.comboBox_value.setObjectName("comboBox_value")
        self.comboBox_value.addItem("")
        self.comboBox_value.addItem("")
        self.comboBox_value.addItem("")
        self.comboBox_value.addItem("")
        self.comboBox_value.addItem("")
        self.comboBox_value.addItem("")
        self.comboBox_value.addItem("")
        self.comboBox_value.addItem("")
        self.comboBox_value.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_value, 11, 0, 1, 1)
        self.comboBox_fre = QtWidgets.QComboBox(self.leftWidget)
        self.comboBox_fre.setObjectName("comboBox_fre")
        self.comboBox_fre.addItem("")
        self.comboBox_fre.addItem("")
        self.comboBox_fre.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_fre, 13, 0, 1, 1)
        self.comboBox_bandwidth = QtWidgets.QComboBox(self.leftWidget)
        self.comboBox_bandwidth.setObjectName("comboBox_bandwidth")
        self.comboBox_bandwidth.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_bandwidth, 15, 0, 1, 1)
        self.gridLayout.addWidget(self.leftWidget, 1, 0, 2, 1)
        self.bottomWidget = QtWidgets.QWidget(self.centralwidget)
        self.bottomWidget.setObjectName("bottomWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.bottomWidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.max_pass_train_speed = QtWidgets.QLabel(self.bottomWidget)
        self.max_pass_train_speed.setObjectName("max_pass_train_speed")
        self.verticalLayout.addWidget(self.max_pass_train_speed)
        self.max_pass_train_speed_val = QtWidgets.QLabel(self.bottomWidget)
        self.max_pass_train_speed_val.setObjectName("max_pass_train_speed_val")
        self.verticalLayout.addWidget(self.max_pass_train_speed_val)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.real_time_speed = QtWidgets.QLabel(self.bottomWidget)
        self.real_time_speed.setObjectName("real_time_speed")
        self.verticalLayout_2.addWidget(self.real_time_speed)
        self.real_time_speed_val = QtWidgets.QLabel(self.bottomWidget)
        self.real_time_speed_val.setObjectName("real_time_speed_val")
        self.verticalLayout_2.addWidget(self.real_time_speed_val)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.left_symmetry = QtWidgets.QLabel(self.bottomWidget)
        self.left_symmetry.setObjectName("left_symmetry")
        self.verticalLayout_3.addWidget(self.left_symmetry)
        self.left_symmetry_val = QtWidgets.QLabel(self.bottomWidget)
        self.left_symmetry_val.setObjectName("left_symmetry_val")
        self.verticalLayout_3.addWidget(self.left_symmetry_val)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.right_symmetry = QtWidgets.QLabel(self.bottomWidget)
        self.right_symmetry.setObjectName("right_symmetry")
        self.verticalLayout_4.addWidget(self.right_symmetry)
        self.right_symmetry_val = QtWidgets.QLabel(self.bottomWidget)
        self.right_symmetry_val.setObjectName("right_symmetry_val")
        self.verticalLayout_4.addWidget(self.right_symmetry_val)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 3, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.muscle_tension = QtWidgets.QLabel(self.bottomWidget)
        self.muscle_tension.setObjectName("muscle_tension")
        self.verticalLayout_5.addWidget(self.muscle_tension)
        self.muscle_tension_val = QtWidgets.QLabel(self.bottomWidget)
        self.muscle_tension_val.setObjectName("muscle_tension_val")
        self.verticalLayout_5.addWidget(self.muscle_tension_val)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 4, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.train_time = QtWidgets.QLabel(self.bottomWidget)
        self.train_time.setObjectName("train_time")
        self.verticalLayout_6.addWidget(self.train_time)
        self.train_time_val = QtWidgets.QLabel(self.bottomWidget)
        self.train_time_val.setObjectName("train_time_val")
        self.verticalLayout_6.addWidget(self.train_time_val)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pass_train_time = QtWidgets.QLabel(self.bottomWidget)
        self.pass_train_time.setObjectName("pass_train_time")
        self.verticalLayout_7.addWidget(self.pass_train_time)
        self.pass_train_time_val = QtWidgets.QLabel(self.bottomWidget)
        self.pass_train_time_val.setObjectName("pass_train_time_val")
        self.verticalLayout_7.addWidget(self.pass_train_time_val)
        self.gridLayout_5.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.active_train_time = QtWidgets.QLabel(self.bottomWidget)
        self.active_train_time.setObjectName("active_train_time")
        self.verticalLayout_8.addWidget(self.active_train_time)
        self.active_train_time_val = QtWidgets.QLabel(self.bottomWidget)
        self.active_train_time_val.setObjectName("active_train_time_val")
        self.verticalLayout_8.addWidget(self.active_train_time_val)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 1, 2, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.avg_power = QtWidgets.QLabel(self.bottomWidget)
        self.avg_power.setObjectName("avg_power")
        self.verticalLayout_9.addWidget(self.avg_power)
        self.avg_power_val = QtWidgets.QLabel(self.bottomWidget)
        self.avg_power_val.setObjectName("avg_power_val")
        self.verticalLayout_9.addWidget(self.avg_power_val)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 1, 3, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.peak_power = QtWidgets.QLabel(self.bottomWidget)
        self.peak_power.setObjectName("peak_power")
        self.verticalLayout_10.addWidget(self.peak_power)
        self.peak_power_val = QtWidgets.QLabel(self.bottomWidget)
        self.peak_power_val.setObjectName("peak_power_val")
        self.verticalLayout_10.addWidget(self.peak_power_val)
        self.gridLayout_5.addLayout(self.verticalLayout_10, 1, 4, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.right_angle = QtWidgets.QLabel(self.bottomWidget)
        self.right_angle.setObjectName("right_angle")
        self.verticalLayout_11.addWidget(self.right_angle)
        self.right_angle_val = QtWidgets.QLabel(self.bottomWidget)
        self.right_angle_val.setObjectName("right_angle_val")
        self.verticalLayout_11.addWidget(self.right_angle_val)
        self.gridLayout_5.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.bottomWidget, 2, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 6)
        self.gridLayout.setColumnStretch(2, 6)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 10)
        self.gridLayout.setRowStretch(2, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signal_max_label2.setText(_translate("MainWindow", "最大信号："))
        self.signal_min_label2.setText(_translate("MainWindow", "最小信号："))
        self.signal_max_val2.setText(_translate("MainWindow", "0"))
        self.signal_min_val2.setText(_translate("MainWindow", "0"))
        self.average_label2.setText(_translate("MainWindow", "平均频率："))
        self.gradient_label2.setText(_translate("MainWindow", "斜率变化率："))
        self.average_val2.setText(_translate("MainWindow", "0"))
        self.gradient_val2.setText(_translate("MainWindow", "0"))
        self.rightWidgetTile.setText(_translate("MainWindow", "右肢"))
        self.energy_entropy_label2.setText(_translate("MainWindow", "能量熵："))
        self.energy_entropy_val2.setText(_translate("MainWindow", "0"))
        self.pectral_entropy_label2.setText(_translate("MainWindow", "频谱熵："))
        self.pectral_entropy_val2.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">上下肢肌电智能优化康复系统</p></body></html>"))
        self.midWidgetTile.setText(_translate("MainWindow", "左肢"))
        self.energy_entropy_label.setText(_translate("MainWindow", "能量熵："))
        self.energy_entropy_val.setText(_translate("MainWindow", "0"))
        self.pectral_entropy_label.setText(_translate("MainWindow", "频谱熵："))
        self.pectral_entropy_val.setText(_translate("MainWindow", "0"))
        self.signal_max_label.setText(_translate("MainWindow", "最大信号："))
        self.signal_min_label.setText(_translate("MainWindow", "最小信号："))
        self.signal_max_val.setText(_translate("MainWindow", "0"))
        self.signal_min_val.setText(_translate("MainWindow", "0"))
        self.average_label.setText(_translate("MainWindow", "平均频率："))
        self.gradient_label.setText(_translate("MainWindow", "斜率变化率："))
        self.average_val.setText(_translate("MainWindow", "0"))
        self.gradient_val.setText(_translate("MainWindow", "0"))
        self.zw1.setText(_translate("MainWindow", "电刺激强度"))
        self.fatigueaBtn_2.setText(_translate("MainWindow", "疲劳标记"))
        self.saveBtn_2.setText(_translate("MainWindow", "保存"))
        self.zw2.setText(_translate("MainWindow", "电刺激频率"))
        self.zw3.setText(_translate("MainWindow", "电刺激脉宽"))
        self.saveBtn_1.setText(_translate("MainWindow", "保存"))
        self.openBtn_2.setText(_translate("MainWindow", "打开"))
        self.fatigueaBtn_1.setText(_translate("MainWindow", "疲劳标记"))
        self.openBtn_1.setText(_translate("MainWindow", "打开"))
        self.left_label_1.setText(_translate("MainWindow", "串口1"))
        self.left_label_2.setText(_translate("MainWindow", "串口2"))
        self.comboBox_value.setItemText(0, _translate("MainWindow", "10mA"))
        self.comboBox_value.setItemText(1, _translate("MainWindow", "20mA"))
        self.comboBox_value.setItemText(2, _translate("MainWindow", "30mA"))
        self.comboBox_value.setItemText(3, _translate("MainWindow", "40mA"))
        self.comboBox_value.setItemText(4, _translate("MainWindow", "50mA"))
        self.comboBox_value.setItemText(5, _translate("MainWindow", "60mA"))
        self.comboBox_value.setItemText(6, _translate("MainWindow", "70mA"))
        self.comboBox_value.setItemText(7, _translate("MainWindow", "80mA"))
        self.comboBox_value.setItemText(8, _translate("MainWindow", "90mA"))
        self.comboBox_fre.setItemText(0, _translate("MainWindow", "50Hz"))
        self.comboBox_fre.setItemText(1, _translate("MainWindow", "10Hz"))
        self.comboBox_fre.setItemText(2, _translate("MainWindow", "100Hz"))
        self.comboBox_bandwidth.setItemText(0, _translate("MainWindow", "100us"))
        self.max_pass_train_speed.setText(_translate("MainWindow", "被动训练最大速度："))
        self.max_pass_train_speed_val.setText(_translate("MainWindow", "0"))
        self.real_time_speed.setText(_translate("MainWindow", "实时速度："))
        self.real_time_speed_val.setText(_translate("MainWindow", "0"))
        self.left_symmetry.setText(_translate("MainWindow", "左对称性："))
        self.left_symmetry_val.setText(_translate("MainWindow", "0"))
        self.right_symmetry.setText(_translate("MainWindow", "右对称性："))
        self.right_symmetry_val.setText(_translate("MainWindow", "0"))
        self.muscle_tension.setText(_translate("MainWindow", "肌张力："))
        self.muscle_tension_val.setText(_translate("MainWindow", "0"))
        self.train_time.setText(_translate("MainWindow", "训练总时长："))
        self.train_time_val.setText(_translate("MainWindow", "0"))
        self.pass_train_time.setText(_translate("MainWindow", "被动训练时长："))
        self.pass_train_time_val.setText(_translate("MainWindow", "0"))
        self.active_train_time.setText(_translate("MainWindow", "主动训练时长："))
        self.active_train_time_val.setText(_translate("MainWindow", "0"))
        self.avg_power.setText(_translate("MainWindow", "平均功率："))
        self.avg_power_val.setText(_translate("MainWindow", "0"))
        self.peak_power.setText(_translate("MainWindow", "最高功率："))
        self.peak_power_val.setText(_translate("MainWindow", "0"))
        self.right_angle.setText(_translate("MainWindow", "脚踏板角度："))
        self.right_angle_val.setText(_translate("MainWindow", "0"))
